version: '3'
services:
  node:
    build: 
      dockerfile: ./Dockerfile
      context: .
    container_name: trybecash_api
    restart: "always"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - "database"

  database:
    image: mysql:8.0.29
    container_name: trybecash_db
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trybecashdb
    volumes:
      - ./trybecash_script.sql:/docker-entrypoint-initdb.d/trybecash_script.sql
    ports:
      - "3306:3306"